language: node_js
node_js:
  - "13"
  - "14"
dist: trusty
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lint
  - npm run test-headless
  - npm run build --project 'ngx-cable-x'
jobs:
  include:
    - stage: release
      node_js: "14"
      script: ./deploy.sh
stages:
  - test
  - name: release
    if: branch = master
